class PDFSourceConfig:
    LIST = [
        dict(
            group="Population",
            i_group=1,
            title="Age Groups",
            fields=[
                "0-4",
                "5-9",
                "10-14",
                "15-19",
                "20-24",
                "25-29",
                "30-34",
                "35-39",
                "40-44",
                "45-49",
                "50-54",
                "55-59",
                "60-64",
                "65-69",
                "70-74",
                "75-79",
                "80-84",
                "85-89",
                "90-94",
                "95 & above",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Population",
            i_group=2,
            title="Gender",
            fields=["Male", "Female"],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Population",
            i_group=3,
            title="Economic Activity",
            fields=["Employed", "Unemployed", "Economically not active"],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Population",
            i_group=4,
            title="Educational Attainment",
            fields=[
                "Primary",
                "Secondary",
                "G.C.E.(O/L)",
                "G.C.E.(A/L)",
                "Degree and above",
                "No schooling",
            ],
            i_total=1,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=1,
            title="Solid Waste Disposal",
            fields=[
                "Collected by Local Authorities",
                "Burnt by Occupants",
                "Buried by Occupants",
                "Composting by Occupants",
                "Dispose by Occupants into"
                + " Road/River/Canal/Sea/Creek/Forest etc",
                "Other",
            ],
            i_total=1,
            has_gnd_num=True,
        ),
        dict(
            group="Housing",
            i_group=2,
            title="Cooking Fuel",
            fields=[
                "Firewood",
                "Kerosene",
                "Gas",
                "Electricity",
                "Saw dust/Paddy husk/",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=3,
            title="Lighting",
            fields=[
                "Electricity - National Electricity Network",
                "Electricity - Rural Hydro Electricity Projects",
                "Kerosene",
                "Solar power",
                "Bio Gas",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=4,
            title="Drinking water",
            fields=[
                "Protected well within premises",
                "Protected well outside premises",
                "Unprotected well",
                "Tap within unit (main line)",
                "Tap within premises but outside unit (main line)",
                "Tap outside premises (main line)",
                "Rural water projects",
                "Tube well",
                "Bowser",
                "River/ Tank/ Stream etc.",
                "Rain water",
                "Bottled water",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=5,
            title="Tenure",
            fields=[
                "Owned by a household member",
                "Rent/Lease- Government owned",
                "Rent/Lease- Privately owned",
                "Rent free occupied",
                "Encroached",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=6,
            title="Toilet",
            fields=[
                "Water seal and connected to a septic tank",
                "Water seal and connected to a piped sewer system",
                "Pour flush toilet (Not water seal)",
                "Direct pit",
                "Other",
                "Not using a toilet",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=7,
            title="Floor",
            fields=[
                "Cement",
                "Tile/Granite/Terrazo",
                "Mud",
                "Wood",
                "Sand",
                "Concrete",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=8,
            title="Roof",
            fields=[
                "Tile",
                "Asbestos",
                "Concrete",
                "Zink",
                "Aluminium sheet",
                "Metal sheet",
                "Cadjan/Palmyrah/Straw",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=9,
            title="Walls",
            fields=[
                "Brick",
                "Cement block/Stone",
                "Cabook",
                "Soil bricks",
                "Mud",
                "Cadjan/Palmyrah",
                "Plank/Metal Sheet",
                "Other",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=10,
            title="Structure",
            fields=[
                "Single 1 story",
                "Single 2 story",
                "Single 2+ story",
                "Attached house/Annex",
                "Flat",
                "Condominium",
                "Twin house",
                "Row/Line room",
                "Hut/Shanty",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
        dict(
            group="Housing",
            i_group=11,
            title="Housing Unit",
            fields=[
                "Permanent",
                "Semi-permanent",
                "Improvised",
                "Un-classified",
            ],
            i_total=2,
            has_gnd_num=False,
        ),
    ]
